### PR TITLE
add Brigade v2.0.0-alpha.4 post

### PR DESCRIPTION
**Pull request by vdice**
Currently has a date of ~~5/6/21~~ 5/11/21 ... can adjust as needed.

### CODE REVIEW

**Comment by krancour** [comment]
Looks great. My only remaining thought is that maybe we should wrap with a brief paragraph the invites people to kick the tires, provide feedback, etc.

**Comment by vdice** [comment]
Good call @krancour.  Updated!

**Comment by krancour** [comment]
@vdice love the last paragraph!

**Review by krancour — APPROVED** [review]
LGTM, but obviously shouldn't be merged until we cut alpha.4

**Comment by vdice** [comment]
Updated the date to the earliest that this might be posted; can of course revise again.

**Pull request merged**
